[2025-08-29T18:50:33.906+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: etl_P2M3_muhammad_al_ghifari.preprocess_data scheduled__2025-07-05T02:20:00+00:00 [queued]>
[2025-08-29T18:50:34.686+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: etl_P2M3_muhammad_al_ghifari.preprocess_data scheduled__2025-07-05T02:20:00+00:00 [queued]>
[2025-08-29T18:50:34.697+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-08-29T18:50:34.704+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2025-08-29T18:50:34.713+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-08-29T18:50:35.047+0000] {taskinstance.py:1389} INFO - Executing <Task(_PythonDecoratedOperator): preprocess_data> on 2025-07-05 02:20:00+00:00
[2025-08-29T18:50:36.084+0000] {standard_task_runner.py:52} INFO - Started process 449 to run task
[2025-08-29T18:50:36.795+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_P2M3_muhammad_al_ghifari', 'preprocess_data', 'scheduled__2025-07-05T02:20:00+00:00', '--job-id', '248', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_muhammad_al_ghifari_DAG.py', '--cfg-path', '/tmp/tmpsifyqcj4', '--error-file', '/tmp/tmp_zf5syqb']
[2025-08-29T18:50:36.901+0000] {standard_task_runner.py:80} INFO - Job 248: Subtask preprocess_data
[2025-08-29T18:50:52.946+0000] {task_command.py:371} INFO - Running <TaskInstance: etl_P2M3_muhammad_al_ghifari.preprocess_data scheduled__2025-07-05T02:20:00+00:00 [running]> on host b40c5a90b1e4
[2025-08-29T18:51:05.487+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Muhammad Al Ghifari
AIRFLOW_CTX_DAG_ID=etl_P2M3_muhammad_al_ghifari
AIRFLOW_CTX_TASK_ID=preprocess_data
AIRFLOW_CTX_EXECUTION_DATE=2025-07-05T02:20:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-07-05T02:20:00+00:00
[2025-08-29T18:51:13.287+0000] {local_task_job.py:84} ERROR - Received SIGTERM. Terminating subprocesses
[2025-08-29T18:51:13.943+0000] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 449. PIDs of all processes in the group: [449]
[2025-08-29T18:51:13.978+0000] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 449
[2025-08-29T18:51:13.986+0000] {taskinstance.py:1553} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-08-29T18:51:14.994+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/P2M3_muhammad_al_ghifari_DAG.py", line 123, in preprocess_data
    pd.NA, regex=True, inplace=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 5244, in replace
    method=method,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 6610, in replace
    to_replace=to_replace, value=value, inplace=inplace, regex=regex
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 438, in replace
    "replace", to_replace=to_replace, value=value, inplace=inplace, regex=regex
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 327, in apply
    applied = getattr(b, f)(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/internals/blocks.py", line 677, in replace
    if isinstance(values, Categorical):
  File "/usr/local/lib/python3.7/abc.py", line 139, in __instancecheck__
    return _abc_instancecheck(cls, instance)
  File "/usr/local/lib/python3.7/abc.py", line 143, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
  File "/usr/local/lib/python3.7/abc.py", line 143, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1555, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-08-29T18:51:15.319+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=etl_P2M3_muhammad_al_ghifari, task_id=preprocess_data, execution_date=20250705T022000, start_date=20250829T185034, end_date=20250829T185115
[2025-08-29T18:51:15.760+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 248 for task preprocess_data (Task received SIGTERM signal; 449)
[2025-08-29T18:51:16.058+0000] {process_utils.py:75} INFO - Process psutil.Process(pid=449, status='terminated', exitcode=1, started='18:50:35') (449) terminated with exit code 1
[2025-08-29T18:51:16.157+0000] {local_task_job.py:156} INFO - Task exited with return code 143
[2025-08-29T18:51:17.127+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
