[2025-08-29T19:03:41.497+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: etl_P2M3_muhammad_al_ghifari.preprocess_data scheduled__2025-08-09T02:20:00+00:00 [queued]>
[2025-08-29T19:03:41.777+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: etl_P2M3_muhammad_al_ghifari.preprocess_data scheduled__2025-08-09T02:20:00+00:00 [queued]>
[2025-08-29T19:03:41.798+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-08-29T19:03:41.802+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2025-08-29T19:03:41.803+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-08-29T19:03:42.151+0000] {taskinstance.py:1389} INFO - Executing <Task(_PythonDecoratedOperator): preprocess_data> on 2025-08-09 02:20:00+00:00
[2025-08-29T19:03:42.666+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_P2M3_muhammad_al_ghifari', 'preprocess_data', 'scheduled__2025-08-09T02:20:00+00:00', '--job-id', '275', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_muhammad_al_ghifari_DAG.py', '--cfg-path', '/tmp/tmpb3un_lll', '--error-file', '/tmp/tmp85th9f0r']
[2025-08-29T19:03:42.752+0000] {standard_task_runner.py:80} INFO - Job 275: Subtask preprocess_data
[2025-08-29T19:03:42.591+0000] {standard_task_runner.py:52} INFO - Started process 283 to run task
[2025-08-29T19:03:43.196+0000] {local_task_job.py:84} ERROR - Received SIGTERM. Terminating subprocesses
[2025-08-29T19:03:43.262+0000] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 283. PIDs of all processes in the group: [283]
[2025-08-29T19:03:43.263+0000] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 283
[2025-08-29T19:03:43.359+0000] {process_utils.py:75} INFO - Process psutil.Process(pid=283, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='19:03:42') (283) terminated with exit code Negsignal.SIGTERM
[2025-08-29T19:03:43.419+0000] {local_task_job.py:156} INFO - Task exited with return code 143
[2025-08-29T19:03:45.349+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=etl_P2M3_muhammad_al_ghifari, task_id=preprocess_data, execution_date=20250809T022000, start_date=20250829T190341, end_date=20250829T190345
[2025-08-29T19:03:48.891+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
