[2025-08-29T19:03:41.232+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: etl_P2M3_muhammad_al_ghifari.preprocess_data scheduled__2025-08-09T02:10:00+00:00 [queued]>
[2025-08-29T19:03:41.313+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: etl_P2M3_muhammad_al_ghifari.preprocess_data scheduled__2025-08-09T02:10:00+00:00 [queued]>
[2025-08-29T19:03:41.317+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-08-29T19:03:41.319+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2025-08-29T19:03:41.320+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-08-29T19:03:41.414+0000] {taskinstance.py:1389} INFO - Executing <Task(_PythonDecoratedOperator): preprocess_data> on 2025-08-09 02:10:00+00:00
[2025-08-29T19:03:41.464+0000] {standard_task_runner.py:52} INFO - Started process 280 to run task
[2025-08-29T19:03:41.498+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_P2M3_muhammad_al_ghifari', 'preprocess_data', 'scheduled__2025-08-09T02:10:00+00:00', '--job-id', '272', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_muhammad_al_ghifari_DAG.py', '--cfg-path', '/tmp/tmp9_8f9wgs', '--error-file', '/tmp/tmpulyk5a11']
[2025-08-29T19:03:41.504+0000] {standard_task_runner.py:80} INFO - Job 272: Subtask preprocess_data
[2025-08-29T19:03:43.176+0000] {local_task_job.py:84} ERROR - Received SIGTERM. Terminating subprocesses
[2025-08-29T19:03:43.264+0000] {task_command.py:371} INFO - Running <TaskInstance: etl_P2M3_muhammad_al_ghifari.preprocess_data scheduled__2025-08-09T02:10:00+00:00 [running]> on host dfc6b3a208a1
[2025-08-29T19:03:43.281+0000] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 280. PIDs of all processes in the group: [280]
[2025-08-29T19:03:43.312+0000] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 280
[2025-08-29T19:03:43.719+0000] {process_utils.py:75} INFO - Process psutil.Process(pid=280, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='19:03:41') (280) terminated with exit code Negsignal.SIGTERM
[2025-08-29T19:03:43.831+0000] {local_task_job.py:156} INFO - Task exited with return code 143
[2025-08-29T19:03:45.312+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=etl_P2M3_muhammad_al_ghifari, task_id=preprocess_data, execution_date=20250809T021000, start_date=20250829T190341, end_date=20250829T190345
[2025-08-29T19:03:48.834+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
