[2025-08-29T19:03:41.198+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: etl_P2M3_muhammad_al_ghifari.preprocess_data scheduled__2025-08-02T02:20:00+00:00 [queued]>
[2025-08-29T19:03:41.304+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: etl_P2M3_muhammad_al_ghifari.preprocess_data scheduled__2025-08-02T02:20:00+00:00 [queued]>
[2025-08-29T19:03:41.305+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-08-29T19:03:41.307+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2025-08-29T19:03:41.309+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-08-29T19:03:41.439+0000] {taskinstance.py:1389} INFO - Executing <Task(_PythonDecoratedOperator): preprocess_data> on 2025-08-02 02:20:00+00:00
[2025-08-29T19:03:41.469+0000] {standard_task_runner.py:52} INFO - Started process 281 to run task
[2025-08-29T19:03:41.501+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_P2M3_muhammad_al_ghifari', 'preprocess_data', 'scheduled__2025-08-02T02:20:00+00:00', '--job-id', '273', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_muhammad_al_ghifari_DAG.py', '--cfg-path', '/tmp/tmpce31l0p1', '--error-file', '/tmp/tmpawtm0kic']
[2025-08-29T19:03:41.512+0000] {standard_task_runner.py:80} INFO - Job 273: Subtask preprocess_data
[2025-08-29T19:03:43.189+0000] {local_task_job.py:84} ERROR - Received SIGTERM. Terminating subprocesses
[2025-08-29T19:03:43.293+0000] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 281. PIDs of all processes in the group: [281]
[2025-08-29T19:03:43.311+0000] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 281
[2025-08-29T19:03:43.445+0000] {process_utils.py:75} INFO - Process psutil.Process(pid=281, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='19:03:41') (281) terminated with exit code Negsignal.SIGTERM
[2025-08-29T19:03:43.689+0000] {local_task_job.py:156} INFO - Task exited with return code 143
[2025-08-29T19:03:44.440+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=etl_P2M3_muhammad_al_ghifari, task_id=preprocess_data, execution_date=20250802T022000, start_date=20250829T190341, end_date=20250829T190344
[2025-08-29T19:03:48.830+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
